`timescale 1ns/1ps
// Self-checking testbench for khnum_sram_2r1w_64x64 — generated by Khnum
module khnum_sram_2r1w_64x64_tb;
  localparam DEPTH = 64, WIDTH = 64, AW = 6, LANES = 1;
  reg clk = 0;
  always #5 clk = ~clk;
  reg [WIDTH-1:0] shadow [0:DEPTH-1];
  integer i, errors;
  reg [AW-1:0] a;
  reg [63:0] rnd;
  integer rk;
  task randword; begin
    for (rk = 0; rk < 2; rk = rk + 1) rnd[rk*32 +: 32] = $urandom;
  end endtask
  reg we = 0, re0 = 0, re1 = 0;
  reg [AW-1:0] waddr = 0, raddr0 = 0, raddr1 = 0;
  reg [WIDTH-1:0] wdata = 0;
  wire [WIDTH-1:0] rdata0, rdata1;
  khnum_sram_2r1w_64x64 dut (
    .clk(clk), .we(we), .waddr(waddr), .wdata(wdata),
    .re0(re0), .raddr0(raddr0), .rdata0(rdata0),
    .re1(re1), .raddr1(raddr1), .rdata1(rdata1)
  );
  task wr(input [AW-1:0] ta, input [WIDTH-1:0] td, input [LANES-1:0] tm);
    begin
      @(negedge clk);
      we = 1; waddr = ta; wdata = td;
      @(negedge clk);
      we = 0;
      shadow[ta] = td;
    end
  endtask
  reg [AW-1:0] b;
  task rd(input [AW-1:0] ta);
    begin
      b = $urandom % DEPTH;   // exercise the second read port too
      @(negedge clk);
      re0 = 1; raddr0 = ta; re1 = 1; raddr1 = b;
      @(negedge clk);
      re0 = 0; re1 = 0;
      if (rdata0 !== shadow[ta]) begin
        errors = errors + 1;
        $display("KHNUM_TB_FAIL 2r1w.p0 addr=%0d got=%h exp=%h", ta, rdata0, shadow[ta]);
      end
      if (rdata1 !== shadow[b]) begin
        errors = errors + 1;
        $display("KHNUM_TB_FAIL 2r1w.p1 addr=%0d got=%h exp=%h", b, rdata1, shadow[b]);
      end
    end
  endtask
  reg [LANES-1:0] mrnd;
  initial begin
    errors = 0;
    #1;
    // 1. init sweep: seed every address so the shadow model is total
    for (i = 0; i < DEPTH; i = i + 1) begin
      randword; wr(i[AW-1:0], rnd[WIDTH-1:0], {LANES{1'b1}});
    end
    // 2. random phase
    for (i = 0; i < 600; i = i + 1) begin
      randword;
      if (rnd[0]) begin
        a = $urandom % DEPTH;
        randword; mrnd = rnd[LANES-1:0];
        randword; wr(a, rnd[WIDTH-1:0], mrnd);
      end else begin
        a = $urandom % DEPTH; rd(a);
      end
    end
    // 3. final sweep
    for (i = 0; i < DEPTH; i = i + 1) rd(i[AW-1:0]);
    if (errors == 0) $display("KHNUM_TB_PASS");
    else $display("KHNUM_TB_FAIL total=%0d", errors);
    $finish;
  end
endmodule
