// -----------------------------------------------------------------------------
// khnum_sram_1rw_256x32_be — generated by Khnum, the ram-headed god of memory
// kind=sram_1rw depth=256 width=32 byte_en=True | read latency 1, read-first RDW
// https://github.com/Lord1Egypt/Khnum
// -----------------------------------------------------------------------------
// Single port: one shared read/write port, synchronous read.
module khnum_sram_1rw_256x32_be (
  input  wire         clk,
  input  wire         ce,      // chip enable (gates both read and write)
  input  wire         we,      // write enable
  input  wire [7:0]  addr,
  input  wire [31:0]  wdata,
  input  wire [3:0]  wmask,   // per-byte write lane enable
  output reg  [31:0]  rdata    // valid 1 cycle after ce, read-first
);
  reg [31:0] mem [0:255];
  integer lane;
  always @(posedge clk) begin
    if (ce) begin
      if (we) begin
        for (lane = 0; lane < 4; lane = lane + 1) begin
          if (wmask[lane]) mem[addr][lane*8 +: 8] <= wdata[lane*8 +: 8];
        end
      end
      rdata <= mem[addr];
    end
  end
endmodule
