`timescale 1ns/1ps
// Self-checking testbench for khnum_sram_1rw_256x32_be — generated by Khnum
module khnum_sram_1rw_256x32_be_tb;
  localparam DEPTH = 256, WIDTH = 32, AW = 8, LANES = 4;
  reg clk = 0;
  always #5 clk = ~clk;
  reg [LANES-1:0] wmask = 0;
  reg [WIDTH-1:0] shadow [0:DEPTH-1];
  integer i, errors;
  reg [AW-1:0] a;
  integer ln;
  reg [31:0] rnd;
  integer rk;
  task randword; begin
    for (rk = 0; rk < 1; rk = rk + 1) rnd[rk*32 +: 32] = $urandom;
  end endtask
  reg ce = 0, we = 0;
  reg [AW-1:0] addr = 0;
  reg [WIDTH-1:0] wdata = 0;
  wire [WIDTH-1:0] rdata;
  khnum_sram_1rw_256x32_be dut (
    .clk(clk), .ce(ce), .we(we), .addr(addr), .wdata(wdata),
    .wmask(wmask),
    .rdata(rdata)
  );
  task wr(input [AW-1:0] ta, input [WIDTH-1:0] td, input [LANES-1:0] tm);
    begin
      @(negedge clk);
      ce = 1; we = 1; addr = ta; wdata = td;
      wmask = tm;
      @(negedge clk);
      ce = 0; we = 0;
      for (ln = 0; ln < 4; ln = ln + 1)
        if (tm[ln]) shadow[ta][ln*8 +: 8] = td[ln*8 +: 8];
    end
  endtask
  task rd(input [AW-1:0] ta);
    begin
      @(negedge clk);
      ce = 1; we = 0; addr = ta;
      @(negedge clk);
      ce = 0;
      if (rdata !== shadow[ta]) begin
        errors = errors + 1;
        $display("KHNUM_TB_FAIL 1rw addr=%0d got=%h exp=%h", ta, rdata, shadow[ta]);
      end
    end
  endtask
  reg [LANES-1:0] mrnd;
  initial begin
    errors = 0;
    #1;
    // 1. init sweep: seed every address so the shadow model is total
    for (i = 0; i < DEPTH; i = i + 1) begin
      randword; wr(i[AW-1:0], rnd[WIDTH-1:0], {LANES{1'b1}});
    end
    // 2. random phase
    for (i = 0; i < 600; i = i + 1) begin
      randword;
      if (rnd[0]) begin
        a = $urandom % DEPTH;
        randword; mrnd = rnd[LANES-1:0];
        randword; wr(a, rnd[WIDTH-1:0], mrnd);
      end else begin
        a = $urandom % DEPTH; rd(a);
      end
    end
    // 3. final sweep
    for (i = 0; i < DEPTH; i = i + 1) rd(i[AW-1:0]);
    if (errors == 0) $display("KHNUM_TB_PASS");
    else $display("KHNUM_TB_FAIL total=%0d", errors);
    $finish;
  end
endmodule
