// -----------------------------------------------------------------------------
// khnum_sram_2r1w_64x64 — generated by Khnum, the ram-headed god of memory
// kind=sram_2r1w depth=64 width=64 byte_en=False | read latency 1, read-first RDW
// https://github.com/Lord1Egypt/Khnum
// -----------------------------------------------------------------------------
// Triple port: one write port + two independent read ports, same clock.
module khnum_sram_2r1w_64x64 (
  input  wire         clk,
  input  wire         we,
  input  wire [5:0]  waddr,
  input  wire [63:0]  wdata,
  input  wire         re0,
  input  wire [5:0]  raddr0,
  output reg  [63:0]  rdata0,  // valid 1 cycle after re0, read-first
  input  wire         re1,
  input  wire [5:0]  raddr1,
  output reg  [63:0]  rdata1   // valid 1 cycle after re1, read-first
);
  reg [63:0] mem [0:63];
  always @(posedge clk) begin
    if (we) mem[waddr] <= wdata;
    if (re0) rdata0 <= mem[raddr0];
    if (re1) rdata1 <= mem[raddr1];
  end
endmodule
