"""Banking composer — tile one base macro into a larger memory.

A banked memory presents the EXACT same external ports as a monolithic
instance of the requested (depth x width) of that kind, so the standard
testbench drives it unchanged. Internally it instantiates `bank_depth *
bank_width` copies of a single deterministic base macro of geometry
(depth / bank_depth) x (width / bank_width):

  * width banking (lane-concat): each macro owns a contiguous slice of the
    data word; wdata is sliced out, rdata is concatenated back. No address
    decode — every slice sees the same address/control.
  * depth banking (address decode): the top `log2(bank_depth)` address bits
    select a bank; the low bits index within it. Writes gate the selected
    bank's write/chip enable. For synchronous-read kinds the bank-select is
    REGISTERED one cycle so it lines up with the 1-cycle read data; the
    asynchronous register file muxes on the live select instead.

Both axes compose into a grid. Only sram_* and rf_2r1w_ff are bankable
(FIFOs have ordering semantics that tiling would break); byte-enable and ECC
are excluded to keep the wrapper's data path a plain slice/concat.

Everything is Verilog-2001 and lint-clean under `verilator -Wall`. f-strings
throughout (no %%-escaping traps).
"""

import math


def bank_geometry(cfg):
    """(per-bank depth, per-bank width) for a banked Config."""
    return cfg.depth // cfg.bank_depth, cfg.width // cfg.bank_width


def _hdr(cfg, D, W, perd, perw):
    return (
        "// -----------------------------------------------------------------------------\n"
        f"// {cfg.name} — banked {cfg.kind}: {D}(depth) x {W}(width) tiles of "
        f"{perd}x{perw}\n"
        "// generated by Khnum, the ram-headed god of memory\n"
        "// Same ports as a monolithic instance; standard testbench drives it unchanged.\n"
        "// -----------------------------------------------------------------------------\n"
    )


def _hi(sig, aw, sub_aw):
    return f"{sig}[{aw - 1}:{sub_aw}]"


def _lo(sig, sub_aw):
    return f"{sig}[{sub_aw - 1}:0]"


def _wslice(sig, w, perw):
    return f"{sig}[{w * perw} +: {perw}]"


def emit_bank_wrapper(cfg):
    D, W = cfg.bank_depth, cfg.bank_width
    perd, perw = bank_geometry(cfg)
    mac = cfg.name + "_mac"
    aw = cfg.aw
    sub_aw = max(1, math.ceil(math.log2(perd)))
    hi = aw - sub_aw  # == log2(D); 0 when depth banking is off
    if cfg.kind == "sram_1rw":
        return _hdr(cfg, D, W, perd, perw) + _wrap_1rw(cfg, D, W, perd, perw, aw, sub_aw, hi, mac)
    if cfg.kind == "sram_1r1w":
        return _hdr(cfg, D, W, perd, perw) + _wrap_1r1w(cfg, D, W, perd, perw, aw, sub_aw, hi, mac)
    if cfg.kind == "sram_2r1w":
        return _hdr(cfg, D, W, perd, perw) + _wrap_2r1w(cfg, D, W, perd, perw, aw, sub_aw, hi, mac)
    return _hdr(cfg, D, W, perd, perw) + _wrap_rf(cfg, D, W, perd, perw, aw, sub_aw, hi, mac)


def _we_gate(base, addr, aw, sub_aw, hi, d):
    """Per-bank enable: gate `base` by the high-bit bank match (or pass through)."""
    if hi == 0:
        return base
    return f"{base} & ({_hi(addr, aw, sub_aw)} == {hi}'d{d})"


def _read_mux(port, w, perw, hi, live_sel):
    """rdata slice = pick bank d from the packed column. Registered `live_sel`
    for sync kinds; when depth banking is off (hi==0) there is one bank."""
    col = f"rdcol_{port}_{w}"
    dst = _wslice(_rdname(port), w, perw)
    idx = "0" if hi == 0 else f"{live_sel}*{perw}"
    return f"  assign {dst} = {col}[{idx} +: {perw}];"


def _rdname(port):
    return "rdata" if port == "" else "rdata" + port


def _read_columns(W, D, perw, ports):
    lines = []
    for port in ports:
        for w in range(W):
            lines.append(f"  wire [{D * perw - 1}:0] rdcol_{port}_{w};")
    return lines


def _instances(cfg, D, W, perd, perw, aw, sub_aw, hi, mac, port_map):
    """Emit the D*W macro instances. port_map(d, w, port_conns) builds the
    body-specific connections; this handles wdata slicing + rdata columns."""
    lines = []
    for d in range(D):
        for w in range(W):
            conns = port_map(d, w)
            lines.append(f"  {mac} u_b{d}_{w} (")
            lines.append("    " + ",\n    ".join(conns))
            lines.append("  );")
    return lines


def _wrap_1rw(cfg, D, W, perd, perw, aw, sub_aw, hi, mac):
    body = []
    body.append("module %s (" % cfg.name)
    body.append("  input  wire         clk,")
    body.append("  input  wire         ce,")
    body.append("  input  wire         we,")
    body.append(f"  input  wire [{aw - 1}:0]  addr,")
    body.append(f"  input  wire [{cfg.width - 1}:0]  wdata,")
    body.append(f"  output wire [{cfg.width - 1}:0]  rdata")
    body.append(");")
    body += _read_columns(W, D, perw, [""])
    if hi:
        body.append(f"  reg [{hi - 1}:0] rsel;")
        body.append("  always @(posedge clk) if (ce) rsel <= %s;" % _hi("addr", aw, sub_aw))

    def pm(d, w):
        return [
            ".clk(clk)",
            ".ce(%s)" % _we_gate("ce", "addr", aw, sub_aw, hi, d),
            ".we(we)",
            ".addr(%s)" % _lo("addr", sub_aw),
            ".wdata(%s)" % _wslice("wdata", w, perw),
            ".rdata(rdcol__%d[%d +: %d])" % (w, d * perw, perw),
        ]
    body += _instances(cfg, D, W, perd, perw, aw, sub_aw, hi, mac, pm)
    for w in range(W):
        body.append(_read_mux("", w, perw, hi, "rsel"))
    body.append("endmodule")
    return "\n".join(body) + "\n"


def _wrap_1r1w(cfg, D, W, perd, perw, aw, sub_aw, hi, mac):
    body = []
    body.append("module %s (" % cfg.name)
    body.append("  input  wire         clk,")
    body.append("  input  wire         we,")
    body.append(f"  input  wire [{aw - 1}:0]  waddr,")
    body.append(f"  input  wire [{cfg.width - 1}:0]  wdata,")
    body.append("  input  wire         re,")
    body.append(f"  input  wire [{aw - 1}:0]  raddr,")
    body.append(f"  output wire [{cfg.width - 1}:0]  rdata")
    body.append(");")
    body += _read_columns(W, D, perw, [""])
    if hi:
        body.append(f"  reg [{hi - 1}:0] rsel;")
        body.append("  always @(posedge clk) if (re) rsel <= %s;" % _hi("raddr", aw, sub_aw))

    def pm(d, w):
        return [
            ".clk(clk)",
            ".we(%s)" % _we_gate("we", "waddr", aw, sub_aw, hi, d),
            ".waddr(%s)" % _lo("waddr", sub_aw),
            ".wdata(%s)" % _wslice("wdata", w, perw),
            ".re(%s)" % _we_gate("re", "raddr", aw, sub_aw, hi, d),
            ".raddr(%s)" % _lo("raddr", sub_aw),
            ".rdata(rdcol__%d[%d +: %d])" % (w, d * perw, perw),
        ]
    body += _instances(cfg, D, W, perd, perw, aw, sub_aw, hi, mac, pm)
    for w in range(W):
        body.append(_read_mux("", w, perw, hi, "rsel"))
    body.append("endmodule")
    return "\n".join(body) + "\n"


def _wrap_2r1w(cfg, D, W, perd, perw, aw, sub_aw, hi, mac):
    body = []
    body.append("module %s (" % cfg.name)
    body.append("  input  wire         clk,")
    body.append("  input  wire         we,")
    body.append(f"  input  wire [{aw - 1}:0]  waddr,")
    body.append(f"  input  wire [{cfg.width - 1}:0]  wdata,")
    body.append("  input  wire         re0,")
    body.append(f"  input  wire [{aw - 1}:0]  raddr0,")
    body.append(f"  output wire [{cfg.width - 1}:0]  rdata0,")
    body.append("  input  wire         re1,")
    body.append(f"  input  wire [{aw - 1}:0]  raddr1,")
    body.append(f"  output wire [{cfg.width - 1}:0]  rdata1")
    body.append(");")
    body += _read_columns(W, D, perw, ["0", "1"])
    if hi:
        body.append(f"  reg [{hi - 1}:0] rsel0, rsel1;")
        body.append("  always @(posedge clk) if (re0) rsel0 <= %s;" % _hi("raddr0", aw, sub_aw))
        body.append("  always @(posedge clk) if (re1) rsel1 <= %s;" % _hi("raddr1", aw, sub_aw))

    def pm(d, w):
        return [
            ".clk(clk)",
            ".we(%s)" % _we_gate("we", "waddr", aw, sub_aw, hi, d),
            ".waddr(%s)" % _lo("waddr", sub_aw),
            ".wdata(%s)" % _wslice("wdata", w, perw),
            ".re0(%s)" % _we_gate("re0", "raddr0", aw, sub_aw, hi, d),
            ".raddr0(%s)" % _lo("raddr0", sub_aw),
            ".rdata0(rdcol_0_%d[%d +: %d])" % (w, d * perw, perw),
            ".re1(%s)" % _we_gate("re1", "raddr1", aw, sub_aw, hi, d),
            ".raddr1(%s)" % _lo("raddr1", sub_aw),
            ".rdata1(rdcol_1_%d[%d +: %d])" % (w, d * perw, perw),
        ]
    body += _instances(cfg, D, W, perd, perw, aw, sub_aw, hi, mac, pm)
    for w in range(W):
        body.append(_read_mux("0", w, perw, hi, "rsel0"))
        body.append(_read_mux("1", w, perw, hi, "rsel1"))
    body.append("endmodule")
    return "\n".join(body) + "\n"


def _wrap_rf(cfg, D, W, perd, perw, aw, sub_aw, hi, mac):
    body = []
    body.append("module %s (" % cfg.name)
    body.append("  input  wire         clk,")
    body.append("  input  wire         we,")
    body.append(f"  input  wire [{aw - 1}:0]  waddr,")
    body.append(f"  input  wire [{cfg.width - 1}:0]  wdata,")
    body.append(f"  input  wire [{aw - 1}:0]  raddr0,")
    body.append(f"  output wire [{cfg.width - 1}:0]  rdata0,")
    body.append(f"  input  wire [{aw - 1}:0]  raddr1,")
    body.append(f"  output wire [{cfg.width - 1}:0]  rdata1")
    body.append(");")
    body += _read_columns(W, D, perw, ["0", "1"])

    def pm(d, w):
        return [
            ".clk(clk)",
            ".we(%s)" % _we_gate("we", "waddr", aw, sub_aw, hi, d),
            ".waddr(%s)" % _lo("waddr", sub_aw),
            ".wdata(%s)" % _wslice("wdata", w, perw),
            ".raddr0(%s)" % _lo("raddr0", sub_aw),
            ".rdata0(rdcol_0_%d[%d +: %d])" % (w, d * perw, perw),
            ".raddr1(%s)" % _lo("raddr1", sub_aw),
            ".rdata1(rdcol_1_%d[%d +: %d])" % (w, d * perw, perw),
        ]
    body += _instances(cfg, D, W, perd, perw, aw, sub_aw, hi, mac, pm)
    # async read: mux on the LIVE high address bits, no register
    for w in range(W):
        if hi:
            body.append("  assign %s = rdcol_0_%d[%s*%d +: %d];"
                        % (_wslice("rdata0", w, perw), w, _hi("raddr0", aw, sub_aw), perw, perw))
            body.append("  assign %s = rdcol_1_%d[%s*%d +: %d];"
                        % (_wslice("rdata1", w, perw), w, _hi("raddr1", aw, sub_aw), perw, perw))
        else:
            body.append("  assign %s = rdcol_0_%d[0 +: %d];"
                        % (_wslice("rdata0", w, perw), w, perw))
            body.append("  assign %s = rdcol_1_%d[0 +: %d];"
                        % (_wslice("rdata1", w, perw), w, perw))
    body.append("endmodule")
    return "\n".join(body) + "\n"
