"""Hamming SECDED (single-error-correct, double-error-detect) generation.

Layout: codeword cw[m:0] for k data bits, p parity bits (2^p >= k+p+1),
m = k+p. Hamming positions 1..m map to cw[1..m] (parity at power-of-2
positions, data elsewhere); cw[0] is the extended overall-parity bit.

Decode: synd = recomputed parity vector; overall = XOR of the whole codeword.
  overall==1            -> single error at position synd (0 = the overall bit
                           itself); corrected. single_err=1.
  overall==0 && synd!=0 -> uncorrectable double error. double_err=1.
  overall==0 && synd==0 -> clean.

Standalone modules via `khnum ecc --width K`; transparent memory protection
via `khnum gen --kind sram_* ... --ecc` (encode on write, decode on read).
f-strings throughout — no %% escaping traps.
"""

import json


def secded_params(k):
    if k < 4 or k > 1024:
        raise ValueError("ecc data width must be in [4, 1024], got %d" % k)
    p = 1
    while (1 << p) < k + p + 1:
        p += 1
    m = k + p
    data_pos = [pos for pos in range(1, m + 1) if pos & (pos - 1)]
    parity_pos = [1 << i for i in range(p)]
    assert len(data_pos) == k
    return p, m, data_pos, parity_pos


def code_width(k):
    _, m, _, _ = secded_params(k)
    return m + 1


def _xor(terms):
    return " ^ ".join(terms)


def _ecc_hdr(k, cw, p, what):
    return (
        "// -----------------------------------------------------------------------------\n"
        f"// Hamming SECDED {what} for {k}-bit data ({cw}-bit codeword, {p}+1 parity bits)\n"
        "// generated by Khnum, the ram-headed god of memory\n"
        "// https://github.com/Lord1Egypt/Khnum\n"
        "// -----------------------------------------------------------------------------\n"
    )


def emit_secded_enc(k, enc_name):
    p, m, data_pos, parity_pos = secded_params(k)
    cw = m + 1
    enc_parity = []
    for i, pp in enumerate(parity_pos):
        cover = [f"din[{j}]" for j, dp in enumerate(data_pos) if dp & pp]
        enc_parity.append(f"  assign par[{i}] = {_xor(cover)};")
    enc_parity.append("".join(f"  assign cw[{pp}] = par[{i}];\n"
                              for i, pp in enumerate(parity_pos)).rstrip("\n"))
    enc_data = [f"  assign cw[{dp}] = din[{j}];" for j, dp in enumerate(data_pos)]
    nl = "\n"
    return _ecc_hdr(k, cw, p, "encoder") + f"""module {enc_name} (
  input  wire [{k - 1}:0]  din,
  output wire [{cw - 1}:0] cw    // [0]=overall parity, [1..{m}]=Hamming positions
);
  wire [{p - 1}:0] par;
{nl.join(enc_data)}
{nl.join(enc_parity)}
  assign cw[0] = (^din) ^ (^par);   // extended parity, no self-reference
endmodule
"""


def emit_secded_dec(k, dec_name):
    p, m, data_pos, parity_pos = secded_params(k)
    cw = m + 1
    synd_bits = []
    for i, pp in enumerate(parity_pos):
        cover = [f"cw[{q}]" for q in range(1, m + 1) if q & pp]
        synd_bits.append(f"  assign synd[{i}] = {_xor(cover)};")
    dout = [f"  assign dout[{j}] = cw[{dp}] ^ (overall & (synd == {p}'d{dp}));"
            for j, dp in enumerate(data_pos)]
    nl = "\n"
    return _ecc_hdr(k, cw, p, "decoder") + f"""module {dec_name} (
  input  wire [{cw - 1}:0] cw,
  output wire [{k - 1}:0]  dout,        // corrected data
  output wire              single_err,  // one bit flipped — corrected
  output wire              double_err   // two bits flipped — NOT correctable
);
  wire [{p - 1}:0] synd;
  wire overall;
{nl.join(synd_bits)}
  assign overall = ^cw;
  assign single_err = overall;
  assign double_err = ~overall & (synd != {p}'d0);
{nl.join(dout)}
endmodule
"""


def emit_secded_tb(k, enc_name, dec_name, tb_name, trials=25):
    p, m, _, _ = secded_params(k)
    cw = m + 1
    chunks = (k + 31) // 32
    return f"""`timescale 1ns/1ps
// Fault-injection testbench for {enc_name}/{dec_name} — generated by Khnum
// Per trial: clean word, ALL {cw} single-bit flips (must correct),
// ALL {cw * (cw - 1) // 2} two-bit flip pairs (must flag double_err).
module {tb_name};
  localparam K = {k}, CW = {cw};
  localparam [CW-1:0] ONE = {{{{CW - 1{{1'b0}}}}, 1'b1}};
  reg  [K-1:0]  din = 0;
  wire [CW-1:0] cw;
  reg  [CW-1:0] corrupted = 0;
  wire [K-1:0]  dout;
  wire single_err, double_err;
  {enc_name} u_enc (.din(din), .cw(cw));
  {dec_name} u_dec (.cw(corrupted), .dout(dout), .single_err(single_err), .double_err(double_err));
  integer t, i, j, errors;
  reg [{chunks * 32 - 1}:0] rnd;
  integer rk;
  task randword; begin
    for (rk = 0; rk < {chunks}; rk = rk + 1) rnd[rk*32 +: 32] = $urandom;
  end endtask
  task chk(input [K-1:0] xd, input xs, input xdd, input [31:0] tag);
    begin
      if (dout !== xd || single_err !== xs || double_err !== xdd) begin
        errors = errors + 1;
        $display("KHNUM_TB_FAIL tag=%0d din=%h dout=%h s=%b d=%b", tag, din, dout, single_err, double_err);
      end
    end
  endtask
  initial begin
    errors = 0;
    for (t = 0; t < {trials}; t = t + 1) begin
      randword; din = rnd[K-1:0];
      #1;
      corrupted = cw; #1;
      chk(din, 1'b0, 1'b0, 0);                 // clean
      for (i = 0; i < CW; i = i + 1) begin
        corrupted = cw ^ (ONE << i); #1;
        chk(din, 1'b1, 1'b0, 1);               // every 1-bit error corrected
      end
      for (i = 0; i < CW; i = i + 1) begin
        for (j = i + 1; j < CW; j = j + 1) begin
          corrupted = cw ^ (ONE << i) ^ (ONE << j); #1;
          if (double_err !== 1'b1 || single_err !== 1'b0) begin
            errors = errors + 1;
            $display("KHNUM_TB_FAIL pair i=%0d j=%0d s=%b d=%b", i, j, single_err, double_err);
          end
        end
      end
    end
    if (errors == 0) $display("KHNUM_TB_PASS");
    else $display("KHNUM_TB_FAIL total=%0d", errors);
    $finish;
  end
endmodule
"""


def standalone_manifest(k, name):
    p, m, _, _ = secded_params(k)
    return json.dumps({
        "generator": "khnum",
        "kind": "ecc_secded",
        "name": name,
        "data_width": k,
        "code_width": m + 1,
        "parity_bits": p + 1,
        "guarantees": "single-error corrected, double-error detected",
        "views": ["rtl", "tb"],
    }, indent=2) + "\n"


def emit_ecc_wrapper(cfg):
    """Transparent SECDED wrapper around a base sram core (encode on write,
    decode+flag on read). cfg is the user-facing Config (kind=sram_*, ecc=True);
    the core stores code_width-bit words."""
    k = cfg.width
    cwid = code_width(k)
    aw = cfg.aw
    enc = cfg.name + "_secded_enc"
    dec = cfg.name + "_secded_dec"
    core = cfg.name + "_core"
    hdr = (
        "// -----------------------------------------------------------------------------\n"
        f"// {cfg.name} — SECDED-protected {cfg.kind} ({cfg.depth}x{k} data, {cwid}-bit codewords)\n"
        "// generated by Khnum, the ram-headed god of memory\n"
        "// Encode on write, decode+correct on read; err flags follow rdata timing.\n"
        "// -----------------------------------------------------------------------------\n"
    )
    if cfg.kind == "sram_1rw":
        return hdr + f"""module {cfg.name} (
  input  wire          clk,
  input  wire          ce,
  input  wire          we,
  input  wire [{aw - 1}:0]  addr,
  input  wire [{k - 1}:0]  wdata,
  output wire [{k - 1}:0]  rdata,
  output wire          single_err,
  output wire          double_err
);
  wire [{cwid - 1}:0] enc_cw, core_rdata;
  {enc} u_enc (.din(wdata), .cw(enc_cw));
  {core} u_core (.clk(clk), .ce(ce), .we(we), .addr(addr), .wdata(enc_cw), .rdata(core_rdata));
  {dec} u_dec (.cw(core_rdata), .dout(rdata), .single_err(single_err), .double_err(double_err));
endmodule
"""
    if cfg.kind == "sram_1r1w":
        return hdr + f"""module {cfg.name} (
  input  wire          clk,
  input  wire          we,
  input  wire [{aw - 1}:0]  waddr,
  input  wire [{k - 1}:0]  wdata,
  input  wire          re,
  input  wire [{aw - 1}:0]  raddr,
  output wire [{k - 1}:0]  rdata,
  output wire          single_err,
  output wire          double_err
);
  wire [{cwid - 1}:0] enc_cw, core_rdata;
  {enc} u_enc (.din(wdata), .cw(enc_cw));
  {core} u_core (.clk(clk), .we(we), .waddr(waddr), .wdata(enc_cw),
                 .re(re), .raddr(raddr), .rdata(core_rdata));
  {dec} u_dec (.cw(core_rdata), .dout(rdata), .single_err(single_err), .double_err(double_err));
endmodule
"""
    # sram_2r1w: one decoder per read port
    return hdr + f"""module {cfg.name} (
  input  wire          clk,
  input  wire          we,
  input  wire [{aw - 1}:0]  waddr,
  input  wire [{k - 1}:0]  wdata,
  input  wire          re0,
  input  wire [{aw - 1}:0]  raddr0,
  output wire [{k - 1}:0]  rdata0,
  output wire          single_err0,
  output wire          double_err0,
  input  wire          re1,
  input  wire [{aw - 1}:0]  raddr1,
  output wire [{k - 1}:0]  rdata1,
  output wire          single_err1,
  output wire          double_err1
);
  wire [{cwid - 1}:0] enc_cw, core_rdata0, core_rdata1;
  {enc} u_enc (.din(wdata), .cw(enc_cw));
  {core} u_core (.clk(clk), .we(we), .waddr(waddr), .wdata(enc_cw),
                 .re0(re0), .raddr0(raddr0), .rdata0(core_rdata0),
                 .re1(re1), .raddr1(raddr1), .rdata1(core_rdata1));
  {dec} u_dec0 (.cw(core_rdata0), .dout(rdata0), .single_err(single_err0), .double_err(double_err0));
  {dec} u_dec1 (.cw(core_rdata1), .dout(rdata1), .single_err(single_err1), .double_err(double_err1));
endmodule
"""
