"""FIFO emitters: single-clock (fifo_sync) and dual-clock CDC (fifo_async).

Both are first-word-fall-through: rdata combinationally shows the head word
whenever !empty (read latency 0). Push at full and pop at empty are ignored.

fifo_async is the standard Cummings architecture: (AW+1)-bit binary+gray
pointers, 2-FF synchronizers in each direction, full = write gray equals
read gray with the two MSBs inverted. Requires power-of-2 depth (enforced
in Config).

These emitters use f-strings, not %-formatting — no `%%` escaping traps.
Literal `%` is fine here.
"""


def emit_fifo(cfg):
    if cfg.kind == "fifo_sync":
        return _emit_fifo_sync(cfg)
    return _emit_fifo_async(cfg)


def emit_fifo_tb(cfg, n_random=600):
    if cfg.kind == "fifo_sync":
        return _emit_tb_fifo_sync(cfg, n_random)
    return _emit_tb_fifo_async(cfg)


def _hdr(cfg, doc):
    return (
        "// -----------------------------------------------------------------------------\n"
        f"// {cfg.name} — generated by Khnum, the ram-headed god of memory\n"
        f"// kind={cfg.kind} depth={cfg.depth} width={cfg.width} | first-word-fall-through\n"
        "// https://github.com/Lord1Egypt/Khnum\n"
        "// -----------------------------------------------------------------------------\n"
        f"{doc}"
    )


def _emit_fifo_sync(cfg):
    d, w, aw = cfg.depth, cfg.width, cfg.aw
    cw = aw + 1  # count width
    doc = ("// Single-clock FIFO. FWFT: rdata is the head word whenever !empty.\n"
           "// push@full and pop@empty are safely ignored. Synchronous active-low reset.\n")
    return _hdr(cfg, doc) + f"""module {cfg.name} (
  input  wire            clk,
  input  wire            rst_n,   // synchronous, active-low
  input  wire            push,
  input  wire [{w-1}:0]  wdata,
  input  wire            pop,
  output wire [{w-1}:0]  rdata,   // head word, valid when !empty (FWFT)
  output wire            full,
  output wire            empty,
  output wire [{cw-1}:0] level    // current occupancy, 0..{d}
);
  reg [{w-1}:0] mem [0:{d-1}];
  reg [{aw-1}:0] wptr, rptr;
  reg [{cw-1}:0] count;
  wire do_push = push && !full;
  wire do_pop  = pop  && !empty;
  assign full  = (count == {cw}'d{d});
  assign empty = (count == {cw}'d0);
  assign level = count;
  assign rdata = mem[rptr];
  always @(posedge clk) begin
    if (!rst_n) begin
      wptr  <= {aw}'d0;
      rptr  <= {aw}'d0;
      count <= {cw}'d0;
    end else begin
      if (do_push) begin
        mem[wptr] <= wdata;
        wptr <= (wptr == {aw}'d{d-1}) ? {aw}'d0 : wptr + {aw}'d1;
      end
      if (do_pop)
        rptr <= (rptr == {aw}'d{d-1}) ? {aw}'d0 : rptr + {aw}'d1;
      count <= count + {{{cw-1}'d0, do_push}} - {{{cw-1}'d0, do_pop}};
    end
  end
`ifdef FORMAL
  // Khnum FIFO safety proof (P2): starting from reset, occupancy never over- or
  // under-flows. Discharged by yosys+z3 BMC, mutation-checked (drop the overflow
  // guard and this fails). Invisible to Verilator/synthesis.
  initial assume (!rst_n);
  always @(posedge clk) if (rst_n) assert (count <= {cw}'d{d});
`endif
endmodule
"""


def _emit_fifo_async(cfg):
    d, w, aw = cfg.depth, cfg.width, cfg.aw
    pw = aw + 1  # pointer width (extra wrap bit)
    doc = ("// Dual-clock (CDC) FIFO — Cummings architecture: gray-coded pointers,\n"
           "// 2-FF synchronizers each direction. FWFT on the read side.\n"
           "// Each domain has its own synchronous active-low reset; release both\n"
           "// before first use.\n")
    return _hdr(cfg, doc) + f"""module {cfg.name} (
  // write domain
  input  wire           wclk,
  input  wire           wrst_n,
  input  wire           push,
  input  wire [{w-1}:0] wdata,
  output wire           full,
  // read domain
  input  wire           rclk,
  input  wire           rrst_n,
  input  wire           pop,
  output wire [{w-1}:0] rdata,   // head word, valid when !empty (FWFT)
  output wire           empty
);
  reg [{w-1}:0] mem [0:{d-1}];
  reg [{pw-1}:0] wbin, wgray, rbin, rgray;
  reg [{pw-1}:0] wq1_rgray, wq2_rgray;   // rgray -> wclk domain (2-FF)
  reg [{pw-1}:0] rq1_wgray, rq2_wgray;   // wgray -> rclk domain (2-FF)
  wire do_push = push && !full;
  wire do_pop  = pop  && !empty;
  wire [{pw-1}:0] wbin_next  = wbin + {{{pw-1}'d0, do_push}};
  wire [{pw-1}:0] wgray_next = (wbin_next >> 1) ^ wbin_next;
  wire [{pw-1}:0] rbin_next  = rbin + {{{pw-1}'d0, do_pop}};
  wire [{pw-1}:0] rgray_next = (rbin_next >> 1) ^ rbin_next;
  assign full  = (wgray == {{~wq2_rgray[{pw-1}:{pw-2}], wq2_rgray[{pw-3}:0]}});
  assign empty = (rgray == rq2_wgray);
  assign rdata = mem[rbin[{aw-1}:0]];
  always @(posedge wclk) begin
    if (!wrst_n) begin
      wbin      <= {pw}'d0;
      wgray     <= {pw}'d0;
      wq1_rgray <= {pw}'d0;
      wq2_rgray <= {pw}'d0;
    end else begin
      if (do_push) mem[wbin[{aw-1}:0]] <= wdata;
      wbin      <= wbin_next;
      wgray     <= wgray_next;
      wq1_rgray <= rgray;
      wq2_rgray <= wq1_rgray;
    end
  end
  always @(posedge rclk) begin
    if (!rrst_n) begin
      rbin      <= {pw}'d0;
      rgray     <= {pw}'d0;
      rq1_wgray <= {pw}'d0;
      rq2_wgray <= {pw}'d0;
    end else begin
      rbin      <= rbin_next;
      rgray     <= rgray_next;
      rq1_wgray <= wgray;
      rq2_wgray <= rq1_wgray;
    end
  end
`ifdef FORMAL
  // Khnum async-FIFO gray-pointer proof (P2): each domain's gray register is
  // always the valid gray encoding of its binary counter, which implies it
  // changes by exactly one bit per step (the property CDC synchronizers rely
  // on to be metastability-safe). Mutation-checked: encode with an identity
  // map instead of (n>>1)^n and this fails.
  initial assume (!wrst_n);
  initial assume (!rrst_n);
  always @(posedge wclk) if (wrst_n) assert (wgray == ((wbin >> 1) ^ wbin));
  always @(posedge rclk) if (rrst_n) assert (rgray == ((rbin >> 1) ^ rbin));
`endif
endmodule
"""


def _rand_decl(cfg):
    chunks = (cfg.width + 31) // 32
    return (
        f"  reg [{chunks * 32 - 1}:0] rnd;\n"
        "  integer rk;\n"
        "  task randword; begin\n"
        f"    for (rk = 0; rk < {chunks}; rk = rk + 1) rnd[rk*32 +: 32] = $urandom;\n"
        "  end endtask\n"
    )


def _emit_tb_fifo_sync(cfg, n_random):
    d, w, aw = cfg.depth, cfg.width, cfg.aw
    cw = aw + 1
    return f"""`timescale 1ns/1ps
// Self-checking testbench for {cfg.name} — generated by Khnum
// Covers: fill to full (+ignored pushes), drain to empty (+ignored pops),
// random push/pop/simultaneous phase; flags and level checked every op.
module {cfg.name}_tb;
  localparam DEPTH = {d}, WIDTH = {w};
  reg clk = 0;
  always #5 clk = ~clk;
  reg rst_n = 0;
  reg push = 0, pop = 0;
  reg [WIDTH-1:0] wdata = 0;
  wire [WIDTH-1:0] rdata;
  wire full, empty;
  wire [{cw - 1}:0] level;
  {cfg.name} dut (
    .clk(clk), .rst_n(rst_n), .push(push), .wdata(wdata),
    .pop(pop), .rdata(rdata), .full(full), .empty(empty), .level(level)
  );
  // shadow circular queue (independent golden model)
  reg [WIDTH-1:0] q [0:DEPTH-1];
  integer qw, qr, qc, i, errors;
  reg fullb, emptyb;
  reg [WIDTH-1:0] datab;
{_rand_decl(cfg)}
  task chkflags;
    begin
      if (full !== (qc == DEPTH)) begin
        errors = errors + 1; $display("KHNUM_TB_FAIL full flag: qc=%0d full=%b", qc, full);
      end
      if (empty !== (qc == 0)) begin
        errors = errors + 1; $display("KHNUM_TB_FAIL empty flag: qc=%0d empty=%b", qc, empty);
      end
      if (level !== qc[{cw - 1}:0]) begin
        errors = errors + 1; $display("KHNUM_TB_FAIL level: qc=%0d level=%0d", qc, level);
      end
      if (qc != 0 && rdata !== q[qr]) begin
        errors = errors + 1; $display("KHNUM_TB_FAIL head: got=%h exp=%h", rdata, q[qr]);
      end
    end
  endtask
  task step(input tpush, input tpop, input [WIDTH-1:0] td);
    begin
      @(negedge clk);
      chkflags;
      fullb = (qc == DEPTH); emptyb = (qc == 0); datab = td;
      push = tpush; pop = tpop; wdata = td;
      @(negedge clk);
      push = 0; pop = 0;
      if (tpush && !fullb) begin
        q[qw] = datab; qw = (qw + 1) % DEPTH; qc = qc + 1;
      end
      if (tpop && !emptyb) begin
        qr = (qr + 1) % DEPTH; qc = qc - 1;
      end
    end
  endtask
  initial begin
    #5000000; $display("KHNUM_TB_FAIL watchdog timeout"); $finish;
  end
  initial begin
    errors = 0; qw = 0; qr = 0; qc = 0;
    repeat (3) @(negedge clk);
    rst_n = 1;
    // 1. fill to full, then 3 pushes that must be ignored
    for (i = 0; i < DEPTH + 3; i = i + 1) begin
      randword; step(1, 0, rnd[WIDTH-1:0]);
    end
    // 2. drain to empty, then 3 pops that must be ignored
    for (i = 0; i < DEPTH + 3; i = i + 1) step(0, 1, {{WIDTH{{1'b0}}}});
    // 3. random phase incl. simultaneous push+pop at every occupancy
    for (i = 0; i < {n_random}; i = i + 1) begin
      randword;
      if (rnd[0] & rnd[1]) begin randword; step(1, 1, rnd[WIDTH-1:0]); end
      else if (rnd[0])     begin randword; step(1, 0, rnd[WIDTH-1:0]); end
      else                 step(0, 1, {{WIDTH{{1'b0}}}});
    end
    @(negedge clk); chkflags;
    if (errors == 0) $display("KHNUM_TB_PASS");
    else $display("KHNUM_TB_FAIL total=%0d", errors);
    $finish;
  end
endmodule
"""


def _emit_tb_fifo_async(cfg, n_ops=2000):
    w = cfg.width
    return f"""`timescale 1ns/1ps
// Self-checking testbench for {cfg.name} — generated by Khnum
// Two free-running coprime clocks (#7 / #11) hammer the CDC: an independent
// producer pushes {n_ops} random words, a consumer pops and checks strict
// FIFO order against the recorded expectation array.
module {cfg.name}_tb;
  localparam WIDTH = {w}, NOPS = {n_ops};
  reg wclk = 0, rclk = 0;
  always #7  wclk = ~wclk;
  always #11 rclk = ~rclk;
  reg wrst_n = 0, rrst_n = 0;
  reg push = 0, pop = 0;
  reg [WIDTH-1:0] wdata = 0;
  wire [WIDTH-1:0] rdata;
  wire full, empty;
  {cfg.name} dut (
    .wclk(wclk), .wrst_n(wrst_n), .push(push), .wdata(wdata), .full(full),
    .rclk(rclk), .rrst_n(rrst_n), .pop(pop), .rdata(rdata), .empty(empty)
  );
  reg [WIDTH-1:0] exp [0:NOPS-1];
  integer wi, ri, errors;
{_rand_decl(cfg)}
  initial begin
    #9000000; $display("KHNUM_TB_FAIL watchdog timeout wi=%0d ri=%0d", wi, ri); $finish;
  end
  initial begin
    wrst_n = 0; rrst_n = 0;
    #40;
    wrst_n = 1; rrst_n = 1;
  end
  // producer (write domain)
  initial begin
    wi = 0; errors = 0;
    @(posedge wrst_n);
    while (wi < NOPS) begin
      @(negedge wclk);
      if (!full && ($urandom & 3) != 0) begin
        randword;
        exp[wi] = rnd[WIDTH-1:0];
        wdata = exp[wi];
        push = 1;
        wi = wi + 1;
      end else begin
        push = 0;
      end
    end
    @(negedge wclk);
    push = 0;
  end
  // consumer (read domain) — FWFT: check head BEFORE popping
  initial begin
    ri = 0;
    @(posedge rrst_n);
    while (ri < NOPS) begin
      @(negedge rclk);
      if (!empty && ($urandom & 3) != 0) begin
        if (rdata !== exp[ri]) begin
          errors = errors + 1;
          $display("KHNUM_TB_FAIL order idx=%0d got=%h exp=%h", ri, rdata, exp[ri]);
        end
        pop = 1;
        ri = ri + 1;
      end else begin
        pop = 0;
      end
    end
    @(negedge rclk);
    pop = 0;
    if (errors == 0) $display("KHNUM_TB_PASS");
    else $display("KHNUM_TB_FAIL total=%0d", errors);
    $finish;
  end
endmodule
"""
