"""Verilog-2001 RTL emitters for Khnum memory primitives.

Design rules (do not break these — they are what makes Khnum portable):
  * Emit plain Verilog-2001: works in Verilator, Icarus, Yosys, and every
    commercial tool. No SystemVerilog in generated DUT code.
  * One `always` block per memory array (Verilator rejects multi-driven
    memories from separate processes).
  * Read-first semantics everywhere: read-during-write to the same address
    returns the OLD data. This is the safest default and maps to both
    Xilinx/Lattice BRAM and standard-cell RAM.
  * Byte-enable writes use an indexed part-select for-loop, which both
    synthesizes cleanly and infers BRAM byte-write enables.
"""

import json
import math

KINDS = ("sram_1rw", "sram_1r1w", "sram_2r1w", "rf_2r1w_ff", "fifo_sync", "fifo_async")

RF_MAX_DEPTH = 64  # flop-based register files get expensive fast


class Config:
    """Validated configuration for one memory instance."""

    def __init__(self, kind, depth, width, byte_en=False, name=None):
        if kind not in KINDS:
            raise ValueError("unknown kind %r (choose from %s)" % (kind, ", ".join(KINDS)))
        if depth < 2 or depth > (1 << 24):
            raise ValueError("depth must be in [2, 2^24], got %d" % depth)
        if width < 1 or width > 4096:
            raise ValueError("width must be in [1, 4096], got %d" % width)
        if byte_en and width % 8 != 0:
            raise ValueError("--byte-en requires width to be a multiple of 8, got %d" % width)
        if kind == "rf_2r1w_ff" and depth > RF_MAX_DEPTH:
            raise ValueError("rf_2r1w_ff is flop-based; depth capped at %d (use sram_2r1w "
                             "for deeper arrays), got %d" % (RF_MAX_DEPTH, depth))
        if kind.startswith("fifo") and byte_en:
            raise ValueError("--byte-en makes no sense on FIFOs (whole words only)")
        if kind == "fifo_async" and (depth < 4 or depth & (depth - 1)):
            raise ValueError("fifo_async requires power-of-2 depth >= 4 (gray-coded "
                             "pointers), got %d" % depth)
        self.kind = kind
        self.depth = depth
        self.width = width
        self.byte_en = byte_en
        self.name = name or "khnum_%s_%dx%d%s" % (kind, depth, width, "_be" if byte_en else "")
        self.aw = max(1, math.ceil(math.log2(depth)))
        self.lanes = width // 8 if byte_en else 1

    def manifest(self):
        async_read = self.kind in ("rf_2r1w_ff", "fifo_sync", "fifo_async")
        return {
            "generator": "khnum",
            "kind": self.kind,
            "name": self.name,
            "depth": self.depth,
            "width": self.width,
            "byte_en": self.byte_en,
            "addr_width": self.aw,
            "write_lanes": self.lanes,
            "read_latency": 0 if async_read else 1,
            "rdw_behavior": "first-word-fall-through" if self.kind.startswith("fifo")
                            else "read-first (old data)",
            "views": ["rtl", "tb"],
        }

    def manifest_json(self):
        return json.dumps(self.manifest(), indent=2) + "\n"


def _header(cfg, ports_doc):
    return (
        "// -----------------------------------------------------------------------------\n"
        "// %s — generated by Khnum, the ram-headed god of memory\n"
        "// kind=%s depth=%d width=%d byte_en=%s | read latency 1, read-first RDW\n"
        "// https://github.com/Lord1Egypt/Khnum\n"
        "// -----------------------------------------------------------------------------\n"
        "%s" % (cfg.name, cfg.kind, cfg.depth, cfg.width, cfg.byte_en, ports_doc)
    )


def _write_block(cfg, we_expr, addr_sig, data_sig, mask_sig):
    """Write logic; byte-enabled writes use a for-loop of lane part-selects."""
    if cfg.byte_en:
        return (
            "      if (%s) begin\n"
            "        for (lane = 0; lane < %d; lane = lane + 1) begin\n"
            "          if (%s[lane]) mem[%s][lane*8 +: 8] <= %s[lane*8 +: 8];\n"
            "        end\n"
            "      end\n" % (we_expr, cfg.lanes, mask_sig, addr_sig, data_sig)
        )
    return "      if (%s) mem[%s] <= %s;\n" % (we_expr, addr_sig, data_sig)


def emit_rtl(cfg):
    if cfg.kind == "sram_1rw":
        return _emit_sram_1rw(cfg)
    if cfg.kind == "sram_1r1w":
        return _emit_sram_1r1w(cfg)
    if cfg.kind == "sram_2r1w":
        return _emit_sram_2r1w(cfg)
    if cfg.kind == "rf_2r1w_ff":
        return _emit_rf_2r1w_ff(cfg)
    from .fifo import emit_fifo
    return emit_fifo(cfg)


def _emit_rf_2r1w_ff(cfg):
    mask_port = "  input  wire [%d:0]  wmask,   // per-byte write lane enable\n" % (cfg.lanes - 1) if cfg.byte_en else ""
    doc = "// Flop-based register file: 1 write port + 2 ASYNC (combinational) read ports.\n"
    lane_decl = "  integer lane;\n" if cfg.byte_en else ""
    body = _write_block(cfg, "we", "waddr", "wdata", "wmask")
    return _header(cfg, doc) + (
        "module %s (\n"
        "  input  wire         clk,\n"
        "  input  wire         we,\n"
        "  input  wire [%d:0]  waddr,\n"
        "  input  wire [%d:0]  wdata,\n"
        "%s"
        "  input  wire [%d:0]  raddr0,\n"
        "  output wire [%d:0]  rdata0,  // asynchronous read, latency 0\n"
        "  input  wire [%d:0]  raddr1,\n"
        "  output wire [%d:0]  rdata1   // asynchronous read, latency 0\n"
        ");\n"
        "  reg [%d:0] mem [0:%d];\n"
        "%s"
        "  always @(posedge clk) begin\n"
        "%s"
        "  end\n"
        "  assign rdata0 = mem[raddr0];\n"
        "  assign rdata1 = mem[raddr1];\n"
        "endmodule\n"
        % (cfg.name, cfg.aw - 1, cfg.width - 1, mask_port, cfg.aw - 1,
           cfg.width - 1, cfg.aw - 1, cfg.width - 1,
           cfg.width - 1, cfg.depth - 1, lane_decl,
           _indent_write(body))
    )


def _emit_sram_1rw(cfg):
    mask_port = "  input  wire [%d:0]  wmask,   // per-byte write lane enable\n" % (cfg.lanes - 1) if cfg.byte_en else ""
    doc = "// Single port: one shared read/write port, synchronous read.\n"
    lane_decl = "  integer lane;\n" if cfg.byte_en else ""
    body = _write_block(cfg, "we", "addr", "wdata", "wmask")
    return _header(cfg, doc) + (
        "module %s (\n"
        "  input  wire         clk,\n"
        "  input  wire         ce,      // chip enable (gates both read and write)\n"
        "  input  wire         we,      // write enable\n"
        "  input  wire [%d:0]  addr,\n"
        "  input  wire [%d:0]  wdata,\n"
        "%s"
        "  output reg  [%d:0]  rdata    // valid 1 cycle after ce, read-first\n"
        ");\n"
        "  reg [%d:0] mem [0:%d];\n"
        "%s"
        "  always @(posedge clk) begin\n"
        "    if (ce) begin\n"
        "%s"
        "      rdata <= mem[addr];\n"
        "    end\n"
        "  end\n"
        "endmodule\n"
        % (cfg.name, cfg.aw - 1, cfg.width - 1, mask_port, cfg.width - 1,
           cfg.width - 1, cfg.depth - 1, lane_decl, body)
    )


def _emit_sram_1r1w(cfg):
    mask_port = "  input  wire [%d:0]  wmask,   // per-byte write lane enable\n" % (cfg.lanes - 1) if cfg.byte_en else ""
    doc = "// Dual port: one write port + one read port, same clock, synchronous read.\n"
    lane_decl = "  integer lane;\n" if cfg.byte_en else ""
    body = _write_block(cfg, "we", "waddr", "wdata", "wmask")
    return _header(cfg, doc) + (
        "module %s (\n"
        "  input  wire         clk,\n"
        "  input  wire         we,\n"
        "  input  wire [%d:0]  waddr,\n"
        "  input  wire [%d:0]  wdata,\n"
        "%s"
        "  input  wire         re,\n"
        "  input  wire [%d:0]  raddr,\n"
        "  output reg  [%d:0]  rdata    // valid 1 cycle after re, read-first\n"
        ");\n"
        "  reg [%d:0] mem [0:%d];\n"
        "%s"
        "  always @(posedge clk) begin\n"
        "%s"
        "    if (re) rdata <= mem[raddr];\n"
        "  end\n"
        "endmodule\n"
        % (cfg.name, cfg.aw - 1, cfg.width - 1, mask_port, cfg.aw - 1,
           cfg.width - 1, cfg.width - 1, cfg.depth - 1, lane_decl,
           _indent_write(body))
    )


def _emit_sram_2r1w(cfg):
    mask_port = "  input  wire [%d:0]  wmask,   // per-byte write lane enable\n" % (cfg.lanes - 1) if cfg.byte_en else ""
    doc = "// Triple port: one write port + two independent read ports, same clock.\n"
    lane_decl = "  integer lane;\n" if cfg.byte_en else ""
    body = _write_block(cfg, "we", "waddr", "wdata", "wmask")
    return _header(cfg, doc) + (
        "module %s (\n"
        "  input  wire         clk,\n"
        "  input  wire         we,\n"
        "  input  wire [%d:0]  waddr,\n"
        "  input  wire [%d:0]  wdata,\n"
        "%s"
        "  input  wire         re0,\n"
        "  input  wire [%d:0]  raddr0,\n"
        "  output reg  [%d:0]  rdata0,  // valid 1 cycle after re0, read-first\n"
        "  input  wire         re1,\n"
        "  input  wire [%d:0]  raddr1,\n"
        "  output reg  [%d:0]  rdata1   // valid 1 cycle after re1, read-first\n"
        ");\n"
        "  reg [%d:0] mem [0:%d];\n"
        "%s"
        "  always @(posedge clk) begin\n"
        "%s"
        "    if (re0) rdata0 <= mem[raddr0];\n"
        "    if (re1) rdata1 <= mem[raddr1];\n"
        "  end\n"
        "endmodule\n"
        % (cfg.name, cfg.aw - 1, cfg.width - 1, mask_port, cfg.aw - 1,
           cfg.width - 1, cfg.aw - 1, cfg.width - 1,
           cfg.width - 1, cfg.depth - 1, lane_decl,
           _indent_write(body))
    )


def _indent_write(block):
    """The 1rw emitter nests writes under `if (ce)`; the others sit one level up."""
    out = []
    for line in block.splitlines(True):
        out.append(line[2:] if line.startswith("      ") else line)
    return "".join(out)
