"""Self-checking Verilog testbench emitters.

Every generated memory ships with a testbench that proves it against a
shadow-array golden model:
  1. init sweep  — write every address (full mask),
  2. random phase — mixed random reads/writes (masked when byte_en),
  3. final sweep — read back every address.
Prints KHNUM_TB_PASS on success; any mismatch prints KHNUM_TB_FAIL lines.
Drive on negedge, sample after the following negedge: one cycle of read
latency, race-free in every simulator (Verilator --timing, Icarus, ...).
"""


def _rand_helpers(cfg):
    chunks = (cfg.width + 31) // 32
    return (
        "  reg [%d:0] rnd;\n"
        "  integer rk;\n"
        "  task randword; begin\n"
        "    for (rk = 0; rk < %d; rk = rk + 1) rnd[rk*32 +: 32] = $urandom;\n"
        "  end endtask\n" % (chunks * 32 - 1, chunks)
    )


def _shadow_update(cfg, addr="ta", data="td", mask="tm"):
    if cfg.byte_en:
        return (
            "      for (ln = 0; ln < %d; ln = ln + 1)\n"
            "        if (%s[ln]) shadow[%s][ln*8 +: 8] = %s[ln*8 +: 8];\n"
            % (cfg.lanes, mask, addr, data)
        )
    return "      shadow[%s] = %s;\n" % (addr, data)


def _check(cfg, port_rdata, addr, tag):
    return (
        "      if (%s !== shadow[%s]) begin\n"
        "        errors = errors + 1;\n"
        "        $display(\"KHNUM_TB_FAIL %s addr=%%0d got=%%h exp=%%h\", %s, %s, shadow[%s]);\n"
        "      end\n" % (port_rdata, addr, tag, addr, port_rdata, addr)
    )


def _epilogue(n_random):
    return (
        "  reg [LANES-1:0] mrnd;\n"
        "  initial begin\n"
        "    errors = 0;\n"
        "    #1;\n"
        "    // 1. init sweep: seed every address so the shadow model is total\n"
        "    for (i = 0; i < DEPTH; i = i + 1) begin\n"
        "      randword; wr(i[AW-1:0], rnd[WIDTH-1:0], {LANES{1'b1}});\n"
        "    end\n"
        "    // 2. random phase\n"
        "    for (i = 0; i < %d; i = i + 1) begin\n"
        "      randword;\n"
        "      if (rnd[0]) begin\n"
        "        a = $urandom %% DEPTH;\n"
        "        randword; mrnd = rnd[LANES-1:0];\n"
        "        randword; wr(a, rnd[WIDTH-1:0], mrnd);\n"
        "      end else begin\n"
        "        a = $urandom %% DEPTH; rd(a);\n"
        "      end\n"
        "    end\n"
        "    // 3. final sweep\n"
        "    for (i = 0; i < DEPTH; i = i + 1) rd(i[AW-1:0]);\n"
        "    if (errors == 0) $display(\"KHNUM_TB_PASS\");\n"
        "    else $display(\"KHNUM_TB_FAIL total=%%0d\", errors);\n"
        "    $finish;\n"
        "  end\n"
        "endmodule\n" % n_random
    )


def emit_tb(cfg, n_random=600):
    if cfg.kind == "sram_1rw":
        return _emit_tb_1rw(cfg, n_random)
    if cfg.kind == "sram_1r1w":
        return _emit_tb_1r1w(cfg, n_random)
    if cfg.kind == "sram_2r1w":
        return _emit_tb_2r1w(cfg, n_random)
    if cfg.kind == "rf_2r1w_ff":
        return _emit_tb_rf_2r1w_ff(cfg, n_random)
    from .fifo import emit_fifo_tb
    return emit_fifo_tb(cfg, n_random)


def _common_head(cfg):
    mask_decl = "  reg [LANES-1:0] wmask = 0;\n" if cfg.byte_en else ""
    ln_decl = "  integer ln;\n" if cfg.byte_en else ""
    return (
        "`timescale 1ns/1ps\n"
        "// Self-checking testbench for %s — generated by Khnum\n"
        "module %s_tb;\n"
        "  localparam DEPTH = %d, WIDTH = %d, AW = %d, LANES = %d;\n"
        "  reg clk = 0;\n"
        "  always #5 clk = ~clk;\n"
        "%s"
        "  reg [WIDTH-1:0] shadow [0:DEPTH-1];\n"
        "  integer i, errors;\n"
        "  reg [AW-1:0] a;\n"
        "%s"
        % (cfg.name, cfg.name, cfg.depth, cfg.width, cfg.aw,
           cfg.lanes if cfg.byte_en else 1, mask_decl, ln_decl)
    ) + _rand_helpers(cfg)


def _mask_conn(cfg):
    return "    .wmask(wmask),\n" if cfg.byte_en else ""


def _mask_set(cfg, mask="tm"):
    return "      wmask = %s;\n" % mask if cfg.byte_en else ""


def _wr_task(cfg, set_lines, clr_lines):
    return (
        "  task wr(input [AW-1:0] ta, input [WIDTH-1:0] td, input [LANES-1:0] tm);\n"
        "    begin\n"
        "      @(negedge clk);\n"
        "%s"
        "%s"
        "      @(negedge clk);\n"
        "%s"
        "%s"
        "    end\n"
        "  endtask\n"
        % (set_lines, _mask_set(cfg), clr_lines, _shadow_update(cfg))
    )


def _emit_tb_1rw(cfg, n_random):
    head = _common_head(cfg)
    decls = (
        "  reg ce = 0, we = 0;\n"
        "  reg [AW-1:0] addr = 0;\n"
        "  reg [WIDTH-1:0] wdata = 0;\n"
        "  wire [WIDTH-1:0] rdata;\n"
        "  %s dut (\n"
        "    .clk(clk), .ce(ce), .we(we), .addr(addr), .wdata(wdata),\n"
        "%s"
        "    .rdata(rdata)\n"
        "  );\n" % (cfg.name, _mask_conn(cfg))
    )
    wr = _wr_task(
        cfg,
        "      ce = 1; we = 1; addr = ta; wdata = td;\n",
        "      ce = 0; we = 0;\n",
    )
    rd = (
        "  task rd(input [AW-1:0] ta);\n"
        "    begin\n"
        "      @(negedge clk);\n"
        "      ce = 1; we = 0; addr = ta;\n"
        "      @(negedge clk);\n"
        "      ce = 0;\n"
        "%s"
        "    end\n"
        "  endtask\n" % _check(cfg, "rdata", "ta", "1rw")
    )
    return head + decls + wr + rd + _epilogue(n_random)


def _emit_tb_1r1w(cfg, n_random):
    head = _common_head(cfg)
    decls = (
        "  reg we = 0, re = 0;\n"
        "  reg [AW-1:0] waddr = 0, raddr = 0;\n"
        "  reg [WIDTH-1:0] wdata = 0;\n"
        "  wire [WIDTH-1:0] rdata;\n"
        "  %s dut (\n"
        "    .clk(clk), .we(we), .waddr(waddr), .wdata(wdata),\n"
        "%s"
        "    .re(re), .raddr(raddr), .rdata(rdata)\n"
        "  );\n" % (cfg.name, _mask_conn(cfg))
    )
    wr = _wr_task(
        cfg,
        "      we = 1; waddr = ta; wdata = td;\n",
        "      we = 0;\n",
    )
    rd = (
        "  task rd(input [AW-1:0] ta);\n"
        "    begin\n"
        "      @(negedge clk);\n"
        "      re = 1; raddr = ta;\n"
        "      @(negedge clk);\n"
        "      re = 0;\n"
        "%s"
        "    end\n"
        "  endtask\n" % _check(cfg, "rdata", "ta", "1r1w")
    )
    return head + decls + wr + rd + _epilogue(n_random)


def _emit_tb_rf_2r1w_ff(cfg, n_random):
    head = _common_head(cfg)
    decls = (
        "  reg we = 0;\n"
        "  reg [AW-1:0] waddr = 0, raddr0 = 0, raddr1 = 0;\n"
        "  reg [WIDTH-1:0] wdata = 0;\n"
        "  wire [WIDTH-1:0] rdata0, rdata1;\n"
        "  %s dut (\n"
        "    .clk(clk), .we(we), .waddr(waddr), .wdata(wdata),\n"
        "%s"
        "    .raddr0(raddr0), .rdata0(rdata0),\n"
        "    .raddr1(raddr1), .rdata1(rdata1)\n"
        "  );\n" % (cfg.name, _mask_conn(cfg))
    )
    wr = _wr_task(
        cfg,
        "      we = 1; waddr = ta; wdata = td;\n",
        "      we = 0;\n",
    )
    rd = (
        "  reg [AW-1:0] b;\n"
        "  task rd(input [AW-1:0] ta);\n"
        "    begin\n"
        "      b = $urandom %% DEPTH;\n"
        "      @(negedge clk);\n"
        "      raddr0 = ta; raddr1 = b;\n"
        "      #1;   // combinational settle — async read has 0-cycle latency\n"
        "%s"
        "%s"
        "    end\n"
        "  endtask\n"
        % (_check(cfg, "rdata0", "ta", "rf.p0"), _check(cfg, "rdata1", "b", "rf.p1"))
    )
    return head + decls + wr + rd + _epilogue(n_random)


def _emit_tb_2r1w(cfg, n_random):
    head = _common_head(cfg)
    decls = (
        "  reg we = 0, re0 = 0, re1 = 0;\n"
        "  reg [AW-1:0] waddr = 0, raddr0 = 0, raddr1 = 0;\n"
        "  reg [WIDTH-1:0] wdata = 0;\n"
        "  wire [WIDTH-1:0] rdata0, rdata1;\n"
        "  %s dut (\n"
        "    .clk(clk), .we(we), .waddr(waddr), .wdata(wdata),\n"
        "%s"
        "    .re0(re0), .raddr0(raddr0), .rdata0(rdata0),\n"
        "    .re1(re1), .raddr1(raddr1), .rdata1(rdata1)\n"
        "  );\n" % (cfg.name, _mask_conn(cfg))
    )
    wr = _wr_task(
        cfg,
        "      we = 1; waddr = ta; wdata = td;\n",
        "      we = 0;\n",
    )
    rd = (
        "  reg [AW-1:0] b;\n"
        "  task rd(input [AW-1:0] ta);\n"
        "    begin\n"
        "      b = $urandom %% DEPTH;   // exercise the second read port too\n"
        "      @(negedge clk);\n"
        "      re0 = 1; raddr0 = ta; re1 = 1; raddr1 = b;\n"
        "      @(negedge clk);\n"
        "      re0 = 0; re1 = 0;\n"
        "%s"
        "%s"
        "    end\n"
        "  endtask\n"
        % (_check(cfg, "rdata0", "ta", "2r1w.p0"), _check(cfg, "rdata1", "b", "2r1w.p1"))
    )
    return head + decls + wr + rd + _epilogue(n_random)
