#!/usr/bin/env python3
"""Khnum characterization report — auto-generates docs/CHARACTERIZATION.md
from whatever has been hardened under harden/{logs,reports,results}/.

Reads the same ORFS log/report fields tools/harden.sh's runs produce (all
world-readable even though ORFS writes them as root inside the container):
  - area/utilization: harden/logs/<platform>/<design>/base/6_report.log
  - WNS/worst slack:  harden/reports/<platform>/<design>/base/6_finish.rpt
  - route DRC count:  harden/logs/<platform>/<design>/base/5_2_route.log (the
    LAST "Number of violations = N" from DRT-0199 -- the router's own final
    geometric-DRC tally, separate from antenna violations, which get their
    own column since they're a different, lower-priority check)
  - peak route RAM:   harden/logs/<platform>/<design>/base/5_2_route.log

A design only appears once harden/results/.../base/6_final.gds exists (i.e.
the flow actually reached GDS) -- an in-progress or failed run is silently
skipped rather than reported with missing/garbage numbers.

Run:  python3 tools/characterize.py   # writes docs/CHARACTERIZATION.md
"""

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HARDEN = os.path.join(ROOT, "harden")
OUT = os.path.join(ROOT, "docs", "CHARACTERIZATION.md")


def _read(path):
    if not os.path.exists(path):
        return ""
    with open(path, errors="replace") as fh:
        return fh.read()


def characterize(platform, design):
    base_results = os.path.join(HARDEN, "results", platform, design, "base")
    base_logs = os.path.join(HARDEN, "logs", platform, design, "base")
    base_reports = os.path.join(HARDEN, "reports", platform, design, "base")
    gds = os.path.join(base_results, "6_final.gds")
    if not os.path.exists(gds):
        return None

    report_log = _read(os.path.join(base_logs, "6_report.log"))
    m = re.search(r"Design area\s+([\d.]+)\s*um\^2\s+(\d+)%\s+utilization", report_log)
    area, util = (m.group(1), m.group(2)) if m else ("?", "?")

    finish_rpt = _read(os.path.join(base_reports, "6_finish.rpt"))
    m = re.search(r"wns max\s+(-?[\d.]+)", finish_rpt)
    wns = m.group(1) if m else "?"

    route_log = _read(os.path.join(base_logs, "5_2_route.log"))
    drc_counts = re.findall(r"Number of violations = (\d+)", route_log)
    route_drc = int(drc_counts[-1]) if drc_counts else None
    antenna_counts = re.findall(r"Found (\d+) net violations", route_log)
    antenna = int(antenna_counts[-1]) if antenna_counts else 0
    peaks = re.findall(r"Peak memory:\s*(\d+)KB", route_log)
    peak_gb = "%.2f" % (int(peaks[-1]) / 1024 / 1024) if peaks else "?"

    gds_mb = "%.0f" % (os.path.getsize(gds) / 1024 / 1024)
    closes = wns != "?" and float(wns) >= 0

    return {
        "design": design, "platform": platform, "gds_mb": gds_mb,
        "area": area, "util": util, "wns": wns, "route_drc": route_drc,
        "antenna": antenna, "peak_gb": peak_gb, "closes": closes,
    }


def main():
    rows = []
    for platform_dir in sorted(glob.glob(os.path.join(HARDEN, "results", "*"))):
        platform = os.path.basename(platform_dir)
        for design_dir in sorted(glob.glob(os.path.join(platform_dir, "*"))):
            design = os.path.basename(design_dir)
            row = characterize(platform, design)
            if row:
                rows.append(row)

    lines = [
        "# Khnum — characterization (auto-generated by tools/characterize.py)",
        "",
        "Do not hand-edit — regenerate with `python3 tools/characterize.py`. "
        "Full context and gotchas: `harden/HARDEN_RESULTS.md`.",
        "",
        "| design | platform | GDS (MB) | area (µm²) | util | WNS (ns) | route DRC | antenna | peak route RAM | timing closes |",
        "|--------|----------|---------:|-----------:|:----:|---------:|:---------:|--------:|----------------:|:------:|",
    ]
    for r in rows:
        drc = "%d viol" % r["route_drc"] if r["route_drc"] is not None else "?"
        antenna = "%d" % r["antenna"] if r["antenna"] else "0"
        status = "✅" if r["closes"] else "❌ not yet"
        lines.append(
            "| `%s` | %s | %s | %s | %s%% | %s | %s | %s | %s GB | %s |"
            % (r["design"], r["platform"], r["gds_mb"], r["area"], r["util"],
               r["wns"], drc, antenna, r["peak_gb"], status)
        )
    if not rows:
        lines.append("| _(no hardened designs found yet)_ | | | | | | | | | |")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s (%d design%s)" % (OUT, len(rows), "" if len(rows) == 1 else "s"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
